sonar.projectKey=AlexInLog_ito
sonar.organization=victimsnino

sonar.projectName=ito
sonar.projectVersion=0.0

sonar.sources=include,tests
sonar.coverage.exclusions=tests/**/*
sonar.cpd.exclusions=tests/**/*
sonar.sourceEncoding=UTF-8

sonar.cfamily.llvm-cov.reportPath=build/test_results/coverage.txt

sonar.issue.ignore.allfile=a1
sonar.issue.ignore.allfile.a1.fileRegexp=#include.*catch2
sonar.cfamily.compile-commands=build/compile_commands.json


