name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CONAN_HOME: "${{ github.workspace }}/release/"

jobs: 
  tests:
    strategy:
      matrix:
        config:
        - { name: lint-ubuntu-gcc,   os: ubuntu-latest,  compiler: gcc,          lint: true,  configurePreset: lint, testPreset: tests }
        - { name: lint-ubuntu-clang, os: ubuntu-latest,  compiler: llvm,         lint: true,  configurePreset: lint, testPreset: tests  }
        - { name: lint-windows,      os: windows-latest, compiler: msvc,         lint: false, configurePreset: debug, testPreset: tests   }
        - { name: lint-macos,        os: macos-latest,   compiler: apple-clang,  lint: true,  configurePreset: lint, testPreset: tests   }
        - { name: sanitize-tsan, os: ubuntu-latest,  compiler: llvm,         lint: false,     configurePreset: sanitize-tsan, testPreset: sanitize   }
        - { name: sanitize-asan, os: ubuntu-latest,  compiler: llvm,         lint: false,     configurePreset: sanitize-asan, testPreset: sanitize   }
        - { name: sanitize-lsan, os: ubuntu-latest,  compiler: llvm,         lint: false,     configurePreset: sanitize-lsan, testPreset: sanitize   }
        - { name: sanitize-ubsan, os: ubuntu-latest,  compiler: llvm,         lint: false,    configurePreset: sanitize-ubsan, testPreset: sanitize   }

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Build cache
        uses: actions/cache@v5
        with:
          path: |
            ./build/
            ~/vcpkg
            ~/.cache/vcpkg/archives
            ${{ env.LOCALAPPDATA }}/vcpkg/archives
            ${{ env.APPDATA }}/vcpkg/archives
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ~/.cache/ccache
            ~/.ccache
            ~/.config/ccache
            ~/Library/Caches/ccache
            ${{ env.LOCALAPPDATA }}/ccache
            ${{ env.XDG_CACHE_HOME }}/ccache
          key: ${{ runner.os }}-deps-${{ matrix.config.name }}-${{ hashFiles('**/conanfile.py') }}-${{ hashFiles('**/CMakePresets.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ matrix.config.name }}-

      - name: Setup Cpp
        if: ${{ matrix.config.os != 'windows-latest' }}
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.config.compiler }}
          cmake: true
          ninja: true
          ccache: true
          clang-tidy: ${{ matrix.config.lint }}
          cppcheck: ${{ matrix.config.lint }}

      - name: get conan
        uses: turtlebrowser/get-conan@main
 
      - name: check conan cache
        uses: actions/cache@v5
        id: check_cache
        with:
            path: ${{ env.CONAN_HOME }}
            key: deps-${{ matrix.config.name }}-${{ hashFiles('**/conanfile.py') }}-${{ hashFiles('**/CMakePresets.json') }}

      - name: conan detect profile
        run: |
          conan profile detect --force
 
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.config.configurePreset }}
          buildPreset: build
          testPreset: ${{ matrix.config.testPreset }}
        env:
          VCPKG_ROOT: ''

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Build cache
        uses: actions/cache@v5
        with:
          path: |
            ./build/
            ~/vcpkg
            ~/.cache/vcpkg/archives
            ${{ env.LOCALAPPDATA }}/vcpkg/archives
            ${{ env.APPDATA }}/vcpkg/archives
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ~/.cache/ccache
            ~/.ccache
            ~/.config/ccache
            ~/Library/Caches/ccache
            ${{ env.LOCALAPPDATA }}/ccache
            ${{ env.XDG_CACHE_HOME }}/ccache
          key: ${{ runner.os }}-deps-coverage-${{ hashFiles('**/conanfile.py') }}-${{ hashFiles('**/CMakePresets.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-coverage-
            
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          cmake: true
          ninja: true
          conan: true
          ccache: true
 
      - name: check conan cache
        uses: actions/cache@v5
        id: check_cache
        with:
            path: ${{ env.CONAN_HOME }}
            key: deps-coverage-${{ hashFiles('**/conanfile.py') }}-${{ hashFiles('**/CMakePresets.json') }}

      - name: conan detect profile
        run: |
          conan profile detect --force
 
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: coverage
          buildPreset: build
          testPreset: tests

      - name: Process coverage info
        run: cmake --build build -t coverage
 
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: > 
            --define sonar.cfamily.compile-commands=build/compile_commands.json
